name: msms-choser-env

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pip:
    - argparse
    - pandas
    - xmltodict
    - pyteomics
    - requests
    - lxml
    - pyyaml
